version: "3.9"
services:
  chat-server:
    build:
      context: ChatAppServer
      dockerfile: ChatAppServer/Dockerfile
    container_name: chat-server
    ports:
      - 5002:80
  chat-web-client:
    build:
      context: ./angular-chat-app-client
      target: development
    volumes:
      - ./angular-chat-app-client/src:/app/src
    container_name: chat-web-client
    ports:
      - 4200:4200
      - 49153:49153
    command: ["npm", "start"]